import type { Service } from '../types'

export const services: Service[] = [
  {
    slug: 'mandado',
    name: 'Mandado',
    shortDescription: 'Compras y recados dentro de Ocotal.',
    description: 'Recogemos y entregamos lo que necesites dentro de Ocotal. Si el mandado tiene varias paradas, cada parada adicional se cobra por separado.',
    pricingType: 'fixed',
    basePrice: 40,
    priceNote: 'C$40 por parada, más el costo de lo que envíe el cliente.',
    coverage: ['ocotal', 'zona-norte'],
    icon: 'ShoppingBag',
    perStop: true,
    askContent: true,
  },
  {
    slug: 'delivery',
    name: 'Delivery',
    shortDescription: 'Entrega de productos y paquetes en Ocotal.',
    description: 'Entregamos paquetes, productos y compras en Ocotal. Varias paradas en un mismo servicio se cobran C$40 por cada parada, más el costo de lo enviado.',
    pricingType: 'fixed',
    basePrice: 40,
    priceNote: 'C$40 por parada, más el costo de lo enviado.',
    coverage: ['ocotal', 'zona-norte'],
    icon: 'Package',
    perStop: true,
    askContent: true,
  },
  {
    slug: 'encomienda',
    name: 'Encomienda',
    shortDescription: 'Envíos de paquetes y cajas a otras zonas.',
    description: 'Enviamos encomiendas a la zona norte, central y pacífico de Nicaragua. El contenido del paquete debe especificarse al solicitar.',
    pricingType: 'fixed',
    basePrice: 40,
    priceNote: 'C$40 por parada, más el costo de lo enviado.',
    coverage: ['ocotal', 'zona-norte', 'zona-central', 'zona-pacifico'],
    icon: 'Box',
    perStop: true,
    askContent: true,
  },
  {
    slug: 'viaje-expreso',
    name: 'Viaje Expreso',
    shortDescription: 'Traslados exprés a la zona norte, central y pacífico.',
    description: 'Viajes exprés a donde necesites. El precio se cotiza según el municipio o departamento, si es solo ida o ida y vuelta, y el tiempo que ocupe el vehículo.',
    pricingType: 'quote',
    basePrice: null,
    priceNote: 'Precio según cotización: municipio, ida o ida-vuelta y tiempo del vehículo.',
    coverage: ['zona-norte', 'zona-central', 'zona-pacifico'],
    icon: 'Zap',
    perStop: false,
    askContent: false,
    quoteFactors: ['municipio', 'tipo de viaje', 'tiempo del vehículo'],
  },
  {
    slug: 'transporte',
    name: 'Transporte',
    shortDescription: 'Transporte de carga y mercadería.',
    description: 'Transportamos carga y mercadería. La cotización considera municipio o departamento, ida o ida y vuelta, y el tiempo que ocupará el vehículo.',
    pricingType: 'quote',
    basePrice: null,
    priceNote: 'Precio según cotización.',
    coverage: ['ocotal', 'zona-norte', 'zona-central', 'zona-pacifico'],
    icon: 'Truck',
    perStop: false,
    askContent: false,
    quoteFactors: ['municipio', 'tipo de viaje', 'tiempo del vehículo'],
  },
  {
    slug: 'acarreo',
    name: 'Acarreo',
    shortDescription: 'Acarreo de materiales y muebles.',
    description: 'Acarreo de materiales, muebles y equipos. Se cotiza según municipio o departamento, ida o ida y vuelta, y tiempo del vehículo.',
    pricingType: 'quote',
    basePrice: null,
    priceNote: 'Precio según cotización.',
    coverage: ['ocotal', 'zona-norte', 'zona-central', 'zona-pacifico'],
    icon: 'Warehouse',
    perStop: false,
    askContent: false,
    quoteFactors: ['municipio', 'tipo de viaje', 'tiempo del vehículo'],
  },
  {
    slug: 'mudanza',
    name: 'Mudanza',
    shortDescription: 'Mudanzas locales y de larga distancia.',
    description: 'Mudanzas completas. La cotización toma en cuenta municipio o departamento, ida o ida y vuelta, y el tiempo del vehículo.',
    pricingType: 'quote',
    basePrice: null,
    priceNote: 'Precio según cotización.',
    coverage: ['ocotal', 'zona-norte', 'zona-central', 'zona-pacifico'],
    icon: 'Home',
    perStop: false,
    askContent: false,
    quoteFactors: ['municipio', 'tipo de viaje', 'tiempo del vehículo'],
  },
]

export function getServiceBySlug(slug: string): Service | undefined {
  return services.find((s) => s.slug === slug)
}